### PR TITLE
FIX: require solutions to be validated and keep track of time on the server.

### LINKED ISSUE #8: [ISSUE]: user can send a custom request and claim any 'time'
### Request on postman
image

### Result on site
image

### Steps to reproduce
- Begin a game 
- Open 'Network' tab from "Inspect"
- Complete the game (manually first)
- View the request that gets made
- Copy the Cookies header and add that to the postman request
- Copy the entire contents of the request and change the value for 'time'
- Submit Request on postman ( or any other similar tool )

### PR DESCRIPTION
**Pull request by crebro**
FIXES ISSUE: #8

This pr considers that the user won't go the extra mile to develop a bot that would solve it anyway. 🙃
Adds an extra layer to protect from the said issue being reproduced.

Changes made:
- add 'solutions' to the item in 'user' collection after a game is created.
- Validate the 'solution' when submitting the solution.
- Server side calculation of the time taken.

### CODE REVIEW

File: src/lib/firestore.ts [hunk 1]
```diff
@@ -127,7 +132,13 @@ export const saveAttempt = async (
   let allWordsFound = (userData.words as string[]).every((word) =>
     foundWords.includes(word)
   );
-  if (!allWordsFound) {
+  let allSolutionsMatch = Object.keys(userData.solutions).every(
+    (word) =>
+      JSON.stringify(userData.solutions[word]) ===
+      JSON.stringify(solutions[word])
+  );
+
```
Comment (NightSling) [inline src/lib/firestore.ts]: JavaScript doesn't guarantee the order of properties when using `JSON.stringify`, which can lead to unexpected results when comparing objects. I recommend using a deep comparison utility like Lodash's `_.isEqual` or manually comparing the two properties `x` and `y`.

File: src/app/api/leaderboard/route.ts [hunk 2]
```diff
@@ -20,18 +20,18 @@ export const POST = auth(async function POST(req) {
 
   const data = (await req.json()) as {
     data: {
-      time: number;
       foundWords: string[];
+      solutions: { [key: string]: string[] };
```
Comment (NightSling) [inline src/app/api/leaderboard/route.ts]: `solutions` is being shared as `{ [key: string]: Position[] };` through the client-side component. Why is it being cast to `string[]` in the API route?

File: src/app/api/leaderboard/route.ts [hunk 3]
```diff
@@ -20,18 +20,18 @@ export const POST = auth(async function POST(req) {
 
   const data = (await req.json()) as {
     data: {
-      time: number;
       foundWords: string[];
```
Comment (NightSling) [inline src/app/api/leaderboard/route.ts]: Since `solutions` subsets `foundWords` through it's keys, I don't think it's a necessity to re-send it.

File: src/lib/wordsearch/WordSearchWrapper.ts [hunk 4]
```diff
@@ -1,4 +1,4 @@
-import { shuffle, merge, difference, cloneDeep } from "lodash";
+import { shuffle, merge, difference, cloneDeep, map } from "lodash";
```
Comment (NightSling) [inline src/lib/wordsearch/WordSearchWrapper.ts]: Optimize the imports

File: src/stores/clientStore.ts [hunk 5]
```diff
@@ -83,8 +85,8 @@ export const useGameStore = create<GameStore>((set, state) => ({
   endGame: () => {
     let endTime = Date.now();
     let dataToSend = {
-      time: endTime - (state().startTime || 0),
-      foundWords: state().alreadyFound,
+      foundWords: Object.keys(state().solutions),
```
Comment (NightSling) [inline src/stores/clientStore.ts]: `solutions` subsets `foundWords`

**Review by NightSling — CHANGES_REQUESTED** [review]
Please resolve the comments.

File: src/stores/clientStore.ts (hunk 5 above)
Comment (crebro) [reply src/stores/clientStore.ts]: resolved.
[latest change](https://github.com/SXC-ALCC/Sherlock-Scrambles-Ts/pull/9/commits/80e8c8305f6b159c8f2da9cca316eeef21c50c02)

File: src/app/api/leaderboard/route.ts (hunk 3 above)
Comment (crebro) [reply src/app/api/leaderboard/route.ts]: resolved.
[latest change](https://github.com/SXC-ALCC/Sherlock-Scrambles-Ts/pull/9/commits/80e8c8305f6b159c8f2da9cca316eeef21c50c02)

File: src/lib/wordsearch/WordSearchWrapper.ts (hunk 4 above)
Comment (crebro) [reply src/lib/wordsearch/WordSearchWrapper.ts]: resolved.
[latest change](https://github.com/SXC-ALCC/Sherlock-Scrambles-Ts/pull/9/commits/80e8c8305f6b159c8f2da9cca316eeef21c50c02)

File: src/lib/firestore.ts (hunk 1 above)
Comment (crebro) [reply src/lib/firestore.ts]: resolved.
[latest change](https://github.com/SXC-ALCC/Sherlock-Scrambles-Ts/pull/9/commits/80e8c8305f6b159c8f2da9cca316eeef21c50c02)

File: src/app/api/leaderboard/route.ts (hunk 2 above)
Comment (crebro) [reply src/app/api/leaderboard/route.ts]: resolved.
[view change](https://github.com/SXC-ALCC/Sherlock-Scrambles-Ts/pull/9/commits/7c63ede2ee46a2861ee91bba50c40d0cc9af6800)

**Review by NightSling — APPROVED** [review]
LGTM!
